# Generated by Django 4.1.1 on 2022-09-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneview_page', '0019_alter_work_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZhixunTeng',
            fields=[
                ('profile_image', models.ImageField(upload_to='')),
                ('name', models.CharField(default='Zhixun Teng', max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
